version: '2'

services:

  user-ms:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - user-db

  user-db:
    image: mysql:5.7.27
    environment:
      MYSQL_DATABASE: express
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: express-mvp-dbuser
      MYSQL_PASSWORD: 123.456
      DATABASE_HOST: user-db
    ports:
      - 3306:3306
    restart: on-failure